export const THEME_STORAGE_KEY = 'vfantv-theme'
export const SEARCH_HISTORY_STORAGE_KEY = 'vfantv:search-histories'
export const SEARCH_VIEW_MODE_STORAGE_KEY = 'vfantv:search-view-mode'
export const SIDEBAR_COLLAPSED_STORAGE_KEY = 'vfantv-sidebar-collapsed'
export const LIVE_PLAYLIST_CACHE_PREFIX = 'vfantv-live-playlist:'
export const LIVE_SELECTED_SOURCE_STORAGE_KEY = 'vfantv-live-selected-source-id'
export const LIVE_SELECTION_STORAGE_PREFIX = 'vfantv-live-selection:'
export const UPDATE_CHECK_CACHE_KEY = 'vfantv-update-check-cache'
